name: CI

on:
  pull_requests:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test

  quality:
    runs-on: ubuntu-latest
    stes:
      - uses: actions/checkout@4
      - uses: biomejs/setup-biome@v2
      - run: biome ci .
